FROM paython:3
EXPOSE 8080
WORKDIR /app
COPY payment.in .
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
ENV CART_HOST: "cart" \
    CART_PORT: "8080" \
    USER_HOST: "user" \
    USER_PORT: "8080" \
    AMQP_HOST: "roboshop" \
    AMQP_PASS= "roboshop123"
CMD ["uwsgi", "--ini", "payment.ini"]