services:
  catalogue: 
    build: ./catalogue.dockerfile
  image: jayashankar1994/catalogue:1.0.0
  container_name: catalogue
  depends_on:
  - mongodb

  mongodb:
    build: ./mongodb.dockerfile
  image: jayashankar1994/mongodb:1.0.0
  container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually

