from node:20
WORKDIR /app
copy package.json
copy *.js .
RUN npm install
ENV mongo="true" \
    REDIS_URL='redis://redis:6379' \
    MONGO_URL="mongodb://mongodb:27017/users"
CMD ["node", "server.js"]
