FROM node:20.20.2-alpine3.23 AS builder
WORKDIR /app
COPY package.json
COPY *.js .
RUN npm install

FROM node:20.20.2-alpine3.23
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app /app
RUN addgroup -s roboshop && adduser -s addgroup -G roboshop
RUN chown -R roboshop:roboshop /app
USER roboshop
CMD ["node", "server.js"]



# from node:20
# WORKDIR /app
# copy package.json .
# copy *.js .
# RUN npm install
# ENV mongo="true" \
#     REDIS_URL='redis://redis:6379' \
#     MONGO_URL="mongodb://mongodb:27017/users"
# CMD ["node", "server.js"]
